/*
Tyrscale Manager API

Testing UpstreamsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package tyrscalesdkgo

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/starton-io/tyrscale/sdk/tyrscale-sdk-go"
)

func Test_tyrscalesdkgo_UpstreamsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test UpstreamsAPIService DeleteUpstream", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routeUuid string
		var uuid string

		resp, httpRes, err := apiClient.UpstreamsAPI.DeleteUpstream(context.Background(), routeUuid, uuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UpstreamsAPIService ListUpstreams", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routeUuid string

		resp, httpRes, err := apiClient.UpstreamsAPI.ListUpstreams(context.Background(), routeUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UpstreamsAPIService UpsertUpstream", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var routeUuid string

		resp, httpRes, err := apiClient.UpstreamsAPI.UpsertUpstream(context.Background(), routeUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
