plugins:
  - name: MyResponseInterceptor
    path: ../plugins/interceptor/response/response.so
    sha256sum: fcfe0885a36c13806fae954eea1bd7fc7bc1dfafceac7d8bece9ab83b087635d
  - name: LoggingMiddleware
    path: ../plugins/middleware/exemple/example.so
    sha256sum: aeef566e98b614978f84e9ef20efbb9eb88deefac8eee00d5498fb3cb70187af