/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CircuitbreakerSettings } from './circuitbreakerSettings';

export class CircuitBreakerConfig {
    'enabled'?: boolean;
    'settings'?: CircuitbreakerSettings;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        },
        {
            "name": "settings",
            "baseName": "settings",
            "type": "CircuitbreakerSettings"
        }    ];

    static getAttributeTypeMap() {
        return CircuitBreakerConfig.attributeTypeMap;
    }
}

