/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { HealthcheckHealthCheckType } from './healthcheckHealthCheckType';

export class HealthCheckConfig {
    'combinedWithCircuitBreaker'?: boolean;
    'enabled'?: boolean;
    'interval'?: number;
    'timeout'?: number;
    'type'?: HealthcheckHealthCheckType;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "combinedWithCircuitBreaker",
            "baseName": "combined_with_circuit_breaker",
            "type": "boolean"
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "number"
        },
        {
            "name": "timeout",
            "baseName": "timeout",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "HealthcheckHealthCheckType"
        }    ];

    static getAttributeTypeMap() {
        return HealthCheckConfig.attributeTypeMap;
    }
}

export namespace HealthCheckConfig {
}
