/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BalancerLoadBalancerStrategy } from './balancerLoadBalancerStrategy';
import { CircuitbreakerSettings } from './circuitbreakerSettings';
import { HealthCheckConfig } from './healthCheckConfig';

export class Route {
    'circuitBreaker'?: CircuitbreakerSettings;
    'healthCheck'?: HealthCheckConfig;
    'host': string;
    'loadBalancerStrategy': BalancerLoadBalancerStrategy;
    'path'?: string;
    'uuid'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "circuitBreaker",
            "baseName": "circuit_breaker",
            "type": "CircuitbreakerSettings"
        },
        {
            "name": "healthCheck",
            "baseName": "health_check",
            "type": "HealthCheckConfig"
        },
        {
            "name": "host",
            "baseName": "host",
            "type": "string"
        },
        {
            "name": "loadBalancerStrategy",
            "baseName": "load_balancer_strategy",
            "type": "BalancerLoadBalancerStrategy"
        },
        {
            "name": "path",
            "baseName": "path",
            "type": "string"
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Route.attributeTypeMap;
    }
}

export namespace Route {
}
