/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum StrategyName {
    StrategyCustom = <any> 'STRATEGY_CUSTOM',
    StrategyHighestBlock = <any> 'STRATEGY_HIGHEST_BLOCK',
    StrategyAirUnderTheCurve = <any> 'STRATEGY_AIR_UNDER_THE_CURVE'
}
