// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/starton-io/tyrscale/manager/api/rpc/dto"
	mock "github.com/stretchr/testify/mock"

	rpc "github.com/starton-io/tyrscale/manager/pkg/pb/rpc"

	upstream "github.com/starton-io/tyrscale/manager/pkg/pb/upstream"
)

// IRPCRepository is an autogenerated mock type for the IRPCRepository type
type IRPCRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *IRPCRepository) Create(ctx context.Context, _a1 *rpc.RpcModel) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *rpc.RpcModel) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, _a1
func (_m *IRPCRepository) Delete(ctx context.Context, _a1 *rpc.RpcModel) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *rpc.RpcModel) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteAssociatedUpstream provides a mock function with given fields: ctx, uuid
func (_m *IRPCRepository) DeleteAssociatedUpstream(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAssociatedUpstream")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, filter
func (_m *IRPCRepository) List(ctx context.Context, filter *dto.ListReq) ([]*rpc.RpcModel, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*rpc.RpcModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ListReq) ([]*rpc.RpcModel, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ListReq) []*rpc.RpcModel); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*rpc.RpcModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.ListReq) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAssociatedUpstream provides a mock function with given fields: ctx, uuid
func (_m *IRPCRepository) ListAssociatedUpstream(ctx context.Context, uuid string) ([]*upstream.UpstreamRPCRouteAssociation, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for ListAssociatedUpstream")
	}

	var r0 []*upstream.UpstreamRPCRouteAssociation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*upstream.UpstreamRPCRouteAssociation, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*upstream.UpstreamRPCRouteAssociation); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*upstream.UpstreamRPCRouteAssociation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *IRPCRepository) Update(ctx context.Context, _a1 *rpc.RpcModel) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *rpc.RpcModel) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIRPCRepository creates a new instance of IRPCRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRPCRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRPCRepository {
	mock := &IRPCRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
