// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/starton-io/tyrscale/manager/api/proxy/upstream/dto"
	mock "github.com/stretchr/testify/mock"

	upstream "github.com/starton-io/tyrscale/manager/pkg/pb/upstream"
)

// IUpstreamService is an autogenerated mock type for the IUpstreamService type
type IUpstreamService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, req
func (_m *IUpstreamService) Delete(ctx context.Context, req *dto.UpstreamDeleteReq) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.UpstreamDeleteReq) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, req
func (_m *IUpstreamService) List(ctx context.Context, req *dto.ListUpstreamReq) ([]*upstream.UpstreamModel, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*upstream.UpstreamModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ListUpstreamReq) ([]*upstream.UpstreamModel, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.ListUpstreamReq) []*upstream.UpstreamModel); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*upstream.UpstreamModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.ListUpstreamReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: ctx, routeUuid, req
func (_m *IUpstreamService) Upsert(ctx context.Context, routeUuid string, req *dto.Upstream) (*dto.UpstreamUpsertRes, error) {
	ret := _m.Called(ctx, routeUuid, req)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 *dto.UpstreamUpsertRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.Upstream) (*dto.UpstreamUpsertRes, error)); ok {
		return rf(ctx, routeUuid, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.Upstream) *dto.UpstreamUpsertRes); ok {
		r0 = rf(ctx, routeUuid, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.UpstreamUpsertRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.Upstream) error); ok {
		r1 = rf(ctx, routeUuid, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIUpstreamService creates a new instance of IUpstreamService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUpstreamService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUpstreamService {
	mock := &IUpstreamService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
