/* tslint:disable */
/* eslint-disable */
/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PluginPluginType } from './PluginPluginType';
import {
    PluginPluginTypeFromJSON,
    PluginPluginTypeFromJSONTyped,
    PluginPluginTypeToJSON,
} from './PluginPluginType';

/**
 * 
 * @export
 * @interface AttachPluginReq
 */
export interface AttachPluginReq {
    /**
     * 
     * @type {object}
     * @memberof AttachPluginReq
     */
    config: object;
    /**
     * 
     * @type {string}
     * @memberof AttachPluginReq
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachPluginReq
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof AttachPluginReq
     */
    priority: number;
    /**
     * 
     * @type {PluginPluginType}
     * @memberof AttachPluginReq
     */
    type: PluginPluginType;
}

/**
 * Check if a given object implements the AttachPluginReq interface.
 */
export function instanceOfAttachPluginReq(value: object): value is AttachPluginReq {
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function AttachPluginReqFromJSON(json: any): AttachPluginReq {
    return AttachPluginReqFromJSONTyped(json, false);
}

export function AttachPluginReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttachPluginReq {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'],
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'],
        'priority': json['priority'],
        'type': PluginPluginTypeFromJSON(json['type']),
    };
}

export function AttachPluginReqToJSON(value?: AttachPluginReq | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'config': value['config'],
        'description': value['description'],
        'name': value['name'],
        'priority': value['priority'],
        'type': PluginPluginTypeToJSON(value['type']),
    };
}

