/* tslint:disable */
/* eslint-disable */
/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateNetworkRes
 */
export interface CreateNetworkRes {
    /**
     * 
     * @type {number}
     * @memberof CreateNetworkRes
     */
    chainId?: number;
}

/**
 * Check if a given object implements the CreateNetworkRes interface.
 */
export function instanceOfCreateNetworkRes(value: object): value is CreateNetworkRes {
    return true;
}

export function CreateNetworkResFromJSON(json: any): CreateNetworkRes {
    return CreateNetworkResFromJSONTyped(json, false);
}

export function CreateNetworkResFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNetworkRes {
    if (json == null) {
        return json;
    }
    return {
        
        'chainId': json['chain_id'] == null ? undefined : json['chain_id'],
    };
}

export function CreateNetworkResToJSON(value?: CreateNetworkRes | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'chain_id': value['chainId'],
    };
}

