/* tslint:disable */
/* eslint-disable */
/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteRpcOptReq
 */
export interface DeleteRpcOptReq {
    /**
     * 
     * @type {boolean}
     * @memberof DeleteRpcOptReq
     */
    cascadeDeleteUpstream?: boolean;
}

/**
 * Check if a given object implements the DeleteRpcOptReq interface.
 */
export function instanceOfDeleteRpcOptReq(value: object): value is DeleteRpcOptReq {
    return true;
}

export function DeleteRpcOptReqFromJSON(json: any): DeleteRpcOptReq {
    return DeleteRpcOptReqFromJSONTyped(json, false);
}

export function DeleteRpcOptReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteRpcOptReq {
    if (json == null) {
        return json;
    }
    return {
        
        'cascadeDeleteUpstream': json['cascade_delete_upstream'] == null ? undefined : json['cascade_delete_upstream'],
    };
}

export function DeleteRpcOptReqToJSON(value?: DeleteRpcOptReq | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'cascade_delete_upstream': value['cascadeDeleteUpstream'],
    };
}

