/* tslint:disable */
/* eslint-disable */
/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetachPluginReq
 */
export interface DetachPluginReq {
    /**
     * 
     * @type {string}
     * @memberof DetachPluginReq
     */
    pluginName: string;
    /**
     * 
     * @type {string}
     * @memberof DetachPluginReq
     */
    pluginType: string;
}

/**
 * Check if a given object implements the DetachPluginReq interface.
 */
export function instanceOfDetachPluginReq(value: object): value is DetachPluginReq {
    if (!('pluginName' in value) || value['pluginName'] === undefined) return false;
    if (!('pluginType' in value) || value['pluginType'] === undefined) return false;
    return true;
}

export function DetachPluginReqFromJSON(json: any): DetachPluginReq {
    return DetachPluginReqFromJSONTyped(json, false);
}

export function DetachPluginReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetachPluginReq {
    if (json == null) {
        return json;
    }
    return {
        
        'pluginName': json['plugin_name'],
        'pluginType': json['plugin_type'],
    };
}

export function DetachPluginReqToJSON(value?: DetachPluginReq | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'plugin_name': value['pluginName'],
        'plugin_type': value['pluginType'],
    };
}

