/* tslint:disable */
/* eslint-disable */
/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoListPluginsResponse
 */
export interface DtoListPluginsResponse {
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof DtoListPluginsResponse
     */
    plugins?: { [key: string]: Array<string>; };
}

/**
 * Check if a given object implements the DtoListPluginsResponse interface.
 */
export function instanceOfDtoListPluginsResponse(value: object): value is DtoListPluginsResponse {
    return true;
}

export function DtoListPluginsResponseFromJSON(json: any): DtoListPluginsResponse {
    return DtoListPluginsResponseFromJSONTyped(json, false);
}

export function DtoListPluginsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoListPluginsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'plugins': json['plugins'] == null ? undefined : json['plugins'],
    };
}

export function DtoListPluginsResponseToJSON(value?: DtoListPluginsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'plugins': value['plugins'],
    };
}

