/* tslint:disable */
/* eslint-disable */
/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Plugin } from './Plugin';
import {
    PluginFromJSON,
    PluginFromJSONTyped,
    PluginToJSON,
} from './Plugin';

/**
 * 
 * @export
 * @interface ListPluginsResponse
 */
export interface ListPluginsResponse {
    /**
     * 
     * @type {{ [key: string]: Plugin; }}
     * @memberof ListPluginsResponse
     */
    plugins?: { [key: string]: Plugin; };
}

/**
 * Check if a given object implements the ListPluginsResponse interface.
 */
export function instanceOfListPluginsResponse(value: object): value is ListPluginsResponse {
    return true;
}

export function ListPluginsResponseFromJSON(json: any): ListPluginsResponse {
    return ListPluginsResponseFromJSONTyped(json, false);
}

export function ListPluginsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPluginsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'plugins': json['plugins'] == null ? undefined : (mapValues(json['plugins'], PluginFromJSON)),
    };
}

export function ListPluginsResponseToJSON(value?: ListPluginsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'plugins': value['plugins'] == null ? undefined : (mapValues(value['plugins'], PluginToJSON)),
    };
}

