/* tslint:disable */
/* eslint-disable */
/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PluginPluginType = {
    PluginTypeResponseInterceptor: 'ResponseInterceptor',
    PluginTypeRequestInterceptor: 'RequestInterceptor',
    PluginTypeMiddleware: 'Middleware'
} as const;
export type PluginPluginType = typeof PluginPluginType[keyof typeof PluginPluginType];


export function instanceOfPluginPluginType(value: any): boolean {
    for (const key in PluginPluginType) {
        if (Object.prototype.hasOwnProperty.call(PluginPluginType, key)) {
            if (PluginPluginType[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PluginPluginTypeFromJSON(json: any): PluginPluginType {
    return PluginPluginTypeFromJSONTyped(json, false);
}

export function PluginPluginTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PluginPluginType {
    return json as PluginPluginType;
}

export function PluginPluginTypeToJSON(value?: PluginPluginType | null): any {
    return value as any;
}

