/* tslint:disable */
/* eslint-disable */
/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StrategyName } from './StrategyName';
import {
    StrategyNameFromJSON,
    StrategyNameFromJSONTyped,
    StrategyNameToJSON,
} from './StrategyName';

/**
 * 
 * @export
 * @interface Recommendation
 */
export interface Recommendation {
    /**
     * 
     * @type {string}
     * @memberof Recommendation
     */
    networkName?: string;
    /**
     * 
     * @type {string}
     * @memberof Recommendation
     */
    routeUuid?: string;
    /**
     * 
     * @type {string}
     * @memberof Recommendation
     */
    schedule?: string;
    /**
     * 
     * @type {StrategyName}
     * @memberof Recommendation
     */
    strategy?: StrategyName;
}

/**
 * Check if a given object implements the Recommendation interface.
 */
export function instanceOfRecommendation(value: object): value is Recommendation {
    return true;
}

export function RecommendationFromJSON(json: any): Recommendation {
    return RecommendationFromJSONTyped(json, false);
}

export function RecommendationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Recommendation {
    if (json == null) {
        return json;
    }
    return {
        
        'networkName': json['network_name'] == null ? undefined : json['network_name'],
        'routeUuid': json['route_uuid'] == null ? undefined : json['route_uuid'],
        'schedule': json['schedule'] == null ? undefined : json['schedule'],
        'strategy': json['strategy'] == null ? undefined : StrategyNameFromJSON(json['strategy']),
    };
}

export function RecommendationToJSON(value?: Recommendation | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'network_name': value['networkName'],
        'route_uuid': value['routeUuid'],
        'schedule': value['schedule'],
        'strategy': StrategyNameToJSON(value['strategy']),
    };
}

