/* tslint:disable */
/* eslint-disable */
/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListPluginsResponse } from './ListPluginsResponse';
import {
    ListPluginsResponseFromJSON,
    ListPluginsResponseFromJSONTyped,
    ListPluginsResponseToJSON,
} from './ListPluginsResponse';

/**
 * 
 * @export
 * @interface ResponsesDefaultSuccessResponseListPluginsResponse
 */
export interface ResponsesDefaultSuccessResponseListPluginsResponse {
    /**
     * 
     * @type {number}
     * @memberof ResponsesDefaultSuccessResponseListPluginsResponse
     */
    code?: number;
    /**
     * 
     * @type {ListPluginsResponse}
     * @memberof ResponsesDefaultSuccessResponseListPluginsResponse
     */
    data?: ListPluginsResponse;
    /**
     * 
     * @type {string}
     * @memberof ResponsesDefaultSuccessResponseListPluginsResponse
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof ResponsesDefaultSuccessResponseListPluginsResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the ResponsesDefaultSuccessResponseListPluginsResponse interface.
 */
export function instanceOfResponsesDefaultSuccessResponseListPluginsResponse(value: object): value is ResponsesDefaultSuccessResponseListPluginsResponse {
    return true;
}

export function ResponsesDefaultSuccessResponseListPluginsResponseFromJSON(json: any): ResponsesDefaultSuccessResponseListPluginsResponse {
    return ResponsesDefaultSuccessResponseListPluginsResponseFromJSONTyped(json, false);
}

export function ResponsesDefaultSuccessResponseListPluginsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesDefaultSuccessResponseListPluginsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : ListPluginsResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ResponsesDefaultSuccessResponseListPluginsResponseToJSON(value?: ResponsesDefaultSuccessResponseListPluginsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'data': ListPluginsResponseToJSON(value['data']),
        'message': value['message'],
        'status': value['status'],
    };
}

