/* tslint:disable */
/* eslint-disable */
/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListUpstreamRes } from './ListUpstreamRes';
import {
    ListUpstreamResFromJSON,
    ListUpstreamResFromJSONTyped,
    ListUpstreamResToJSON,
} from './ListUpstreamRes';

/**
 * 
 * @export
 * @interface ResponsesDefaultSuccessResponseListUpstreamRes
 */
export interface ResponsesDefaultSuccessResponseListUpstreamRes {
    /**
     * 
     * @type {number}
     * @memberof ResponsesDefaultSuccessResponseListUpstreamRes
     */
    code?: number;
    /**
     * 
     * @type {ListUpstreamRes}
     * @memberof ResponsesDefaultSuccessResponseListUpstreamRes
     */
    data?: ListUpstreamRes;
    /**
     * 
     * @type {string}
     * @memberof ResponsesDefaultSuccessResponseListUpstreamRes
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof ResponsesDefaultSuccessResponseListUpstreamRes
     */
    status?: number;
}

/**
 * Check if a given object implements the ResponsesDefaultSuccessResponseListUpstreamRes interface.
 */
export function instanceOfResponsesDefaultSuccessResponseListUpstreamRes(value: object): value is ResponsesDefaultSuccessResponseListUpstreamRes {
    return true;
}

export function ResponsesDefaultSuccessResponseListUpstreamResFromJSON(json: any): ResponsesDefaultSuccessResponseListUpstreamRes {
    return ResponsesDefaultSuccessResponseListUpstreamResFromJSONTyped(json, false);
}

export function ResponsesDefaultSuccessResponseListUpstreamResFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesDefaultSuccessResponseListUpstreamRes {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : ListUpstreamResFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ResponsesDefaultSuccessResponseListUpstreamResToJSON(value?: ResponsesDefaultSuccessResponseListUpstreamRes | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'data': ListUpstreamResToJSON(value['data']),
        'message': value['message'],
        'status': value['status'],
    };
}

