/* tslint:disable */
/* eslint-disable */
/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DtoListPluginsResponse } from './DtoListPluginsResponse';
import {
    DtoListPluginsResponseFromJSON,
    DtoListPluginsResponseFromJSONTyped,
    DtoListPluginsResponseToJSON,
} from './DtoListPluginsResponse';

/**
 * 
 * @export
 * @interface ResponsesDefaultSuccessResponseDtoListPluginsResponse
 */
export interface ResponsesDefaultSuccessResponseDtoListPluginsResponse {
    /**
     * 
     * @type {number}
     * @memberof ResponsesDefaultSuccessResponseDtoListPluginsResponse
     */
    code?: number;
    /**
     * 
     * @type {DtoListPluginsResponse}
     * @memberof ResponsesDefaultSuccessResponseDtoListPluginsResponse
     */
    data?: DtoListPluginsResponse;
    /**
     * 
     * @type {string}
     * @memberof ResponsesDefaultSuccessResponseDtoListPluginsResponse
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof ResponsesDefaultSuccessResponseDtoListPluginsResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the ResponsesDefaultSuccessResponseDtoListPluginsResponse interface.
 */
export function instanceOfResponsesDefaultSuccessResponseDtoListPluginsResponse(value: object): value is ResponsesDefaultSuccessResponseDtoListPluginsResponse {
    return true;
}

export function ResponsesDefaultSuccessResponseDtoListPluginsResponseFromJSON(json: any): ResponsesDefaultSuccessResponseDtoListPluginsResponse {
    return ResponsesDefaultSuccessResponseDtoListPluginsResponseFromJSONTyped(json, false);
}

export function ResponsesDefaultSuccessResponseDtoListPluginsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesDefaultSuccessResponseDtoListPluginsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : DtoListPluginsResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ResponsesDefaultSuccessResponseDtoListPluginsResponseToJSON(value?: ResponsesDefaultSuccessResponseDtoListPluginsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'data': DtoListPluginsResponseToJSON(value['data']),
        'message': value['message'],
        'status': value['status'],
    };
}

