/* tslint:disable */
/* eslint-disable */
/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponsesInternalServerErrorResponse
 */
export interface ResponsesInternalServerErrorResponse {
    /**
     * 
     * @type {number}
     * @memberof ResponsesInternalServerErrorResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponsesInternalServerErrorResponse
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof ResponsesInternalServerErrorResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the ResponsesInternalServerErrorResponse interface.
 */
export function instanceOfResponsesInternalServerErrorResponse(value: object): value is ResponsesInternalServerErrorResponse {
    return true;
}

export function ResponsesInternalServerErrorResponseFromJSON(json: any): ResponsesInternalServerErrorResponse {
    return ResponsesInternalServerErrorResponseFromJSONTyped(json, false);
}

export function ResponsesInternalServerErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesInternalServerErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ResponsesInternalServerErrorResponseToJSON(value?: ResponsesInternalServerErrorResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
        'status': value['status'],
    };
}

