/* tslint:disable */
/* eslint-disable */
/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponsesConflictResponse
 */
export interface ResponsesConflictResponse {
    /**
     * 
     * @type {number}
     * @memberof ResponsesConflictResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof ResponsesConflictResponse
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof ResponsesConflictResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the ResponsesConflictResponse interface.
 */
export function instanceOfResponsesConflictResponse(value: object): value is ResponsesConflictResponse {
    return true;
}

export function ResponsesConflictResponseFromJSON(json: any): ResponsesConflictResponse {
    return ResponsesConflictResponseFromJSONTyped(json, false);
}

export function ResponsesConflictResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesConflictResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ResponsesConflictResponseToJSON(value?: ResponsesConflictResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'message': value['message'],
        'status': value['status'],
    };
}

