/* tslint:disable */
/* eslint-disable */
/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListRecommendationRes } from './ListRecommendationRes';
import {
    ListRecommendationResFromJSON,
    ListRecommendationResFromJSONTyped,
    ListRecommendationResToJSON,
} from './ListRecommendationRes';

/**
 * 
 * @export
 * @interface ResponsesDefaultSuccessResponseListRecommendationRes
 */
export interface ResponsesDefaultSuccessResponseListRecommendationRes {
    /**
     * 
     * @type {number}
     * @memberof ResponsesDefaultSuccessResponseListRecommendationRes
     */
    code?: number;
    /**
     * 
     * @type {ListRecommendationRes}
     * @memberof ResponsesDefaultSuccessResponseListRecommendationRes
     */
    data?: ListRecommendationRes;
    /**
     * 
     * @type {string}
     * @memberof ResponsesDefaultSuccessResponseListRecommendationRes
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof ResponsesDefaultSuccessResponseListRecommendationRes
     */
    status?: number;
}

/**
 * Check if a given object implements the ResponsesDefaultSuccessResponseListRecommendationRes interface.
 */
export function instanceOfResponsesDefaultSuccessResponseListRecommendationRes(value: object): value is ResponsesDefaultSuccessResponseListRecommendationRes {
    return true;
}

export function ResponsesDefaultSuccessResponseListRecommendationResFromJSON(json: any): ResponsesDefaultSuccessResponseListRecommendationRes {
    return ResponsesDefaultSuccessResponseListRecommendationResFromJSONTyped(json, false);
}

export function ResponsesDefaultSuccessResponseListRecommendationResFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesDefaultSuccessResponseListRecommendationRes {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : ListRecommendationResFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ResponsesDefaultSuccessResponseListRecommendationResToJSON(value?: ResponsesDefaultSuccessResponseListRecommendationRes | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'data': ListRecommendationResToJSON(value['data']),
        'message': value['message'],
        'status': value['status'],
    };
}

