/* tslint:disable */
/* eslint-disable */
/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListRouteRes } from './ListRouteRes';
import {
    ListRouteResFromJSON,
    ListRouteResFromJSONTyped,
    ListRouteResToJSON,
} from './ListRouteRes';

/**
 * 
 * @export
 * @interface ResponsesDefaultSuccessResponseListRouteRes
 */
export interface ResponsesDefaultSuccessResponseListRouteRes {
    /**
     * 
     * @type {number}
     * @memberof ResponsesDefaultSuccessResponseListRouteRes
     */
    code?: number;
    /**
     * 
     * @type {ListRouteRes}
     * @memberof ResponsesDefaultSuccessResponseListRouteRes
     */
    data?: ListRouteRes;
    /**
     * 
     * @type {string}
     * @memberof ResponsesDefaultSuccessResponseListRouteRes
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof ResponsesDefaultSuccessResponseListRouteRes
     */
    status?: number;
}

/**
 * Check if a given object implements the ResponsesDefaultSuccessResponseListRouteRes interface.
 */
export function instanceOfResponsesDefaultSuccessResponseListRouteRes(value: object): value is ResponsesDefaultSuccessResponseListRouteRes {
    return true;
}

export function ResponsesDefaultSuccessResponseListRouteResFromJSON(json: any): ResponsesDefaultSuccessResponseListRouteRes {
    return ResponsesDefaultSuccessResponseListRouteResFromJSONTyped(json, false);
}

export function ResponsesDefaultSuccessResponseListRouteResFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesDefaultSuccessResponseListRouteRes {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : ListRouteResFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ResponsesDefaultSuccessResponseListRouteResToJSON(value?: ResponsesDefaultSuccessResponseListRouteRes | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'data': ListRouteResToJSON(value['data']),
        'message': value['message'],
        'status': value['status'],
    };
}

