/* tslint:disable */
/* eslint-disable */
/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListNetworkRes } from './ListNetworkRes';
import {
    ListNetworkResFromJSON,
    ListNetworkResFromJSONTyped,
    ListNetworkResToJSON,
} from './ListNetworkRes';

/**
 * 
 * @export
 * @interface ResponsesDefaultSuccessResponseListNetworkRes
 */
export interface ResponsesDefaultSuccessResponseListNetworkRes {
    /**
     * 
     * @type {number}
     * @memberof ResponsesDefaultSuccessResponseListNetworkRes
     */
    code?: number;
    /**
     * 
     * @type {ListNetworkRes}
     * @memberof ResponsesDefaultSuccessResponseListNetworkRes
     */
    data?: ListNetworkRes;
    /**
     * 
     * @type {string}
     * @memberof ResponsesDefaultSuccessResponseListNetworkRes
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof ResponsesDefaultSuccessResponseListNetworkRes
     */
    status?: number;
}

/**
 * Check if a given object implements the ResponsesDefaultSuccessResponseListNetworkRes interface.
 */
export function instanceOfResponsesDefaultSuccessResponseListNetworkRes(value: object): value is ResponsesDefaultSuccessResponseListNetworkRes {
    return true;
}

export function ResponsesDefaultSuccessResponseListNetworkResFromJSON(json: any): ResponsesDefaultSuccessResponseListNetworkRes {
    return ResponsesDefaultSuccessResponseListNetworkResFromJSONTyped(json, false);
}

export function ResponsesDefaultSuccessResponseListNetworkResFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponsesDefaultSuccessResponseListNetworkRes {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : ListNetworkResFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ResponsesDefaultSuccessResponseListNetworkResToJSON(value?: ResponsesDefaultSuccessResponseListNetworkRes | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'data': ListNetworkResToJSON(value['data']),
        'message': value['message'],
        'status': value['status'],
    };
}

