/* tslint:disable */
/* eslint-disable */
/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HealthcheckHealthCheckConfig } from './HealthcheckHealthCheckConfig';
import {
    HealthcheckHealthCheckConfigFromJSON,
    HealthcheckHealthCheckConfigFromJSONTyped,
    HealthcheckHealthCheckConfigToJSON,
} from './HealthcheckHealthCheckConfig';
import type { BalancerLoadBalancerStrategy } from './BalancerLoadBalancerStrategy';
import {
    BalancerLoadBalancerStrategyFromJSON,
    BalancerLoadBalancerStrategyFromJSONTyped,
    BalancerLoadBalancerStrategyToJSON,
} from './BalancerLoadBalancerStrategy';
import type { CircuitbreakerSettings } from './CircuitbreakerSettings';
import {
    CircuitbreakerSettingsFromJSON,
    CircuitbreakerSettingsFromJSONTyped,
    CircuitbreakerSettingsToJSON,
} from './CircuitbreakerSettings';
import type { Plugins } from './Plugins';
import {
    PluginsFromJSON,
    PluginsFromJSONTyped,
    PluginsToJSON,
} from './Plugins';

/**
 * 
 * @export
 * @interface UpdateRouteReq
 */
export interface UpdateRouteReq {
    /**
     * 
     * @type {CircuitbreakerSettings}
     * @memberof UpdateRouteReq
     */
    circuitBreaker?: CircuitbreakerSettings;
    /**
     * 
     * @type {HealthcheckHealthCheckConfig}
     * @memberof UpdateRouteReq
     */
    healthCheck?: HealthcheckHealthCheckConfig;
    /**
     * Uuid                 string                         `json:"uuid" validate:"required,uuid"`
     * @type {string}
     * @memberof UpdateRouteReq
     */
    host?: string;
    /**
     * 
     * @type {BalancerLoadBalancerStrategy}
     * @memberof UpdateRouteReq
     */
    loadBalancerStrategy?: BalancerLoadBalancerStrategy;
    /**
     * 
     * @type {string}
     * @memberof UpdateRouteReq
     */
    path?: string;
    /**
     * 
     * @type {Plugins}
     * @memberof UpdateRouteReq
     */
    plugins?: Plugins;
}

/**
 * Check if a given object implements the UpdateRouteReq interface.
 */
export function instanceOfUpdateRouteReq(value: object): value is UpdateRouteReq {
    return true;
}

export function UpdateRouteReqFromJSON(json: any): UpdateRouteReq {
    return UpdateRouteReqFromJSONTyped(json, false);
}

export function UpdateRouteReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRouteReq {
    if (json == null) {
        return json;
    }
    return {
        
        'circuitBreaker': json['circuit_breaker'] == null ? undefined : CircuitbreakerSettingsFromJSON(json['circuit_breaker']),
        'healthCheck': json['health_check'] == null ? undefined : HealthcheckHealthCheckConfigFromJSON(json['health_check']),
        'host': json['host'] == null ? undefined : json['host'],
        'loadBalancerStrategy': json['load_balancer_strategy'] == null ? undefined : BalancerLoadBalancerStrategyFromJSON(json['load_balancer_strategy']),
        'path': json['path'] == null ? undefined : json['path'],
        'plugins': json['plugins'] == null ? undefined : PluginsFromJSON(json['plugins']),
    };
}

export function UpdateRouteReqToJSON(value?: UpdateRouteReq | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'circuit_breaker': CircuitbreakerSettingsToJSON(value['circuitBreaker']),
        'health_check': HealthcheckHealthCheckConfigToJSON(value['healthCheck']),
        'host': value['host'],
        'load_balancer_strategy': BalancerLoadBalancerStrategyToJSON(value['loadBalancerStrategy']),
        'path': value['path'],
        'plugins': PluginsToJSON(value['plugins']),
    };
}

