/* tslint:disable */
/* eslint-disable */
/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpstreamFastHTTPSettings
 */
export interface UpstreamFastHTTPSettings {
    /**
     * 
     * @type {string}
     * @memberof UpstreamFastHTTPSettings
     */
    proxyHost?: string;
}

/**
 * Check if a given object implements the UpstreamFastHTTPSettings interface.
 */
export function instanceOfUpstreamFastHTTPSettings(value: object): value is UpstreamFastHTTPSettings {
    return true;
}

export function UpstreamFastHTTPSettingsFromJSON(json: any): UpstreamFastHTTPSettings {
    return UpstreamFastHTTPSettingsFromJSONTyped(json, false);
}

export function UpstreamFastHTTPSettingsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpstreamFastHTTPSettings {
    if (json == null) {
        return json;
    }
    return {
        
        'proxyHost': json['proxy_host'] == null ? undefined : json['proxy_host'],
    };
}

export function UpstreamFastHTTPSettingsToJSON(value?: UpstreamFastHTTPSettings | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'proxy_host': value['proxyHost'],
    };
}

