/* tslint:disable */
/* eslint-disable */
/**
 * Tyrscale Manager API
 * This is the manager service for Tyrscale
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@starton.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Upstream
 */
export interface Upstream {
    /**
     * 
     * @type {string}
     * @memberof Upstream
     */
    host?: string;
    /**
     * 
     * @type {string}
     * @memberof Upstream
     */
    path?: string;
    /**
     * 
     * @type {number}
     * @memberof Upstream
     */
    port?: number;
    /**
     * 
     * @type {string}
     * @memberof Upstream
     */
    rpcUuid?: string;
    /**
     * 
     * @type {string}
     * @memberof Upstream
     */
    scheme?: string;
    /**
     * 
     * @type {string}
     * @memberof Upstream
     */
    uuid?: string;
    /**
     * 
     * @type {number}
     * @memberof Upstream
     */
    weight: number;
}

/**
 * Check if a given object implements the Upstream interface.
 */
export function instanceOfUpstream(value: object): value is Upstream {
    if (!('weight' in value) || value['weight'] === undefined) return false;
    return true;
}

export function UpstreamFromJSON(json: any): Upstream {
    return UpstreamFromJSONTyped(json, false);
}

export function UpstreamFromJSONTyped(json: any, ignoreDiscriminator: boolean): Upstream {
    if (json == null) {
        return json;
    }
    return {
        
        'host': json['host'] == null ? undefined : json['host'],
        'path': json['path'] == null ? undefined : json['path'],
        'port': json['port'] == null ? undefined : json['port'],
        'rpcUuid': json['rpc_uuid'] == null ? undefined : json['rpc_uuid'],
        'scheme': json['scheme'] == null ? undefined : json['scheme'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'weight': json['weight'],
    };
}

export function UpstreamToJSON(value?: Upstream | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'host': value['host'],
        'path': value['path'],
        'port': value['port'],
        'rpc_uuid': value['rpcUuid'],
        'scheme': value['scheme'],
        'uuid': value['uuid'],
        'weight': value['weight'],
    };
}

