/*
Tyrscale Manager API

This is the manager service for Tyrscale

API version: 1.0
Contact: support@starton.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tyrscalesdkgo

import (
	"encoding/json"
)

// checks if the ResponsesBadRequestResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesBadRequestResponse{}

// ResponsesBadRequestResponse struct for ResponsesBadRequestResponse
type ResponsesBadRequestResponse struct {
	Code *int32 `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Status *int32 `json:"status,omitempty"`
}

// NewResponsesBadRequestResponse instantiates a new ResponsesBadRequestResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesBadRequestResponse() *ResponsesBadRequestResponse {
	this := ResponsesBadRequestResponse{}
	return &this
}

// NewResponsesBadRequestResponseWithDefaults instantiates a new ResponsesBadRequestResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesBadRequestResponseWithDefaults() *ResponsesBadRequestResponse {
	this := ResponsesBadRequestResponse{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ResponsesBadRequestResponse) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesBadRequestResponse) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ResponsesBadRequestResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *ResponsesBadRequestResponse) SetCode(v int32) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResponsesBadRequestResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesBadRequestResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResponsesBadRequestResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResponsesBadRequestResponse) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ResponsesBadRequestResponse) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesBadRequestResponse) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ResponsesBadRequestResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *ResponsesBadRequestResponse) SetStatus(v int32) {
	o.Status = &v
}

func (o ResponsesBadRequestResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesBadRequestResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableResponsesBadRequestResponse struct {
	value *ResponsesBadRequestResponse
	isSet bool
}

func (v NullableResponsesBadRequestResponse) Get() *ResponsesBadRequestResponse {
	return v.value
}

func (v *NullableResponsesBadRequestResponse) Set(val *ResponsesBadRequestResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesBadRequestResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesBadRequestResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesBadRequestResponse(val *ResponsesBadRequestResponse) *NullableResponsesBadRequestResponse {
	return &NullableResponsesBadRequestResponse{value: val, isSet: true}
}

func (v NullableResponsesBadRequestResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesBadRequestResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


