/*
Tyrscale Manager API

This is the manager service for Tyrscale

API version: 1.0
Contact: support@starton.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tyrscalesdkgo

import (
	"encoding/json"
)

// checks if the HealthcheckRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthcheckRequest{}

// HealthcheckRequest struct for HealthcheckRequest
type HealthcheckRequest struct {
	Body *string `json:"body,omitempty"`
	Headers *map[string]string `json:"headers,omitempty"`
	Method *string `json:"method,omitempty"`
	StatusCode *int32 `json:"status_code,omitempty"`
}

// NewHealthcheckRequest instantiates a new HealthcheckRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthcheckRequest() *HealthcheckRequest {
	this := HealthcheckRequest{}
	return &this
}

// NewHealthcheckRequestWithDefaults instantiates a new HealthcheckRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthcheckRequestWithDefaults() *HealthcheckRequest {
	this := HealthcheckRequest{}
	return &this
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *HealthcheckRequest) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthcheckRequest) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *HealthcheckRequest) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *HealthcheckRequest) SetBody(v string) {
	o.Body = &v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *HealthcheckRequest) GetHeaders() map[string]string {
	if o == nil || IsNil(o.Headers) {
		var ret map[string]string
		return ret
	}
	return *o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthcheckRequest) GetHeadersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Headers) {
		return nil, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *HealthcheckRequest) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]string and assigns it to the Headers field.
func (o *HealthcheckRequest) SetHeaders(v map[string]string) {
	o.Headers = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *HealthcheckRequest) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthcheckRequest) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *HealthcheckRequest) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *HealthcheckRequest) SetMethod(v string) {
	o.Method = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *HealthcheckRequest) GetStatusCode() int32 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int32
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HealthcheckRequest) GetStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *HealthcheckRequest) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int32 and assigns it to the StatusCode field.
func (o *HealthcheckRequest) SetStatusCode(v int32) {
	o.StatusCode = &v
}

func (o HealthcheckRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthcheckRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	if !IsNil(o.StatusCode) {
		toSerialize["status_code"] = o.StatusCode
	}
	return toSerialize, nil
}

type NullableHealthcheckRequest struct {
	value *HealthcheckRequest
	isSet bool
}

func (v NullableHealthcheckRequest) Get() *HealthcheckRequest {
	return v.value
}

func (v *NullableHealthcheckRequest) Set(val *HealthcheckRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthcheckRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthcheckRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthcheckRequest(val *HealthcheckRequest) *NullableHealthcheckRequest {
	return &NullableHealthcheckRequest{value: val, isSet: true}
}

func (v NullableHealthcheckRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthcheckRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


