/*
Tyrscale Manager API

This is the manager service for Tyrscale

API version: 1.0
Contact: support@starton.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tyrscalesdkgo

import (
	"encoding/json"
)

// checks if the DeleteRpcOptReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteRpcOptReq{}

// DeleteRpcOptReq struct for DeleteRpcOptReq
type DeleteRpcOptReq struct {
	CascadeDeleteUpstream *bool `json:"cascade_delete_upstream,omitempty"`
}

// NewDeleteRpcOptReq instantiates a new DeleteRpcOptReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteRpcOptReq() *DeleteRpcOptReq {
	this := DeleteRpcOptReq{}
	return &this
}

// NewDeleteRpcOptReqWithDefaults instantiates a new DeleteRpcOptReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteRpcOptReqWithDefaults() *DeleteRpcOptReq {
	this := DeleteRpcOptReq{}
	return &this
}

// GetCascadeDeleteUpstream returns the CascadeDeleteUpstream field value if set, zero value otherwise.
func (o *DeleteRpcOptReq) GetCascadeDeleteUpstream() bool {
	if o == nil || IsNil(o.CascadeDeleteUpstream) {
		var ret bool
		return ret
	}
	return *o.CascadeDeleteUpstream
}

// GetCascadeDeleteUpstreamOk returns a tuple with the CascadeDeleteUpstream field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteRpcOptReq) GetCascadeDeleteUpstreamOk() (*bool, bool) {
	if o == nil || IsNil(o.CascadeDeleteUpstream) {
		return nil, false
	}
	return o.CascadeDeleteUpstream, true
}

// HasCascadeDeleteUpstream returns a boolean if a field has been set.
func (o *DeleteRpcOptReq) HasCascadeDeleteUpstream() bool {
	if o != nil && !IsNil(o.CascadeDeleteUpstream) {
		return true
	}

	return false
}

// SetCascadeDeleteUpstream gets a reference to the given bool and assigns it to the CascadeDeleteUpstream field.
func (o *DeleteRpcOptReq) SetCascadeDeleteUpstream(v bool) {
	o.CascadeDeleteUpstream = &v
}

func (o DeleteRpcOptReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteRpcOptReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CascadeDeleteUpstream) {
		toSerialize["cascade_delete_upstream"] = o.CascadeDeleteUpstream
	}
	return toSerialize, nil
}

type NullableDeleteRpcOptReq struct {
	value *DeleteRpcOptReq
	isSet bool
}

func (v NullableDeleteRpcOptReq) Get() *DeleteRpcOptReq {
	return v.value
}

func (v *NullableDeleteRpcOptReq) Set(val *DeleteRpcOptReq) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteRpcOptReq) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteRpcOptReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteRpcOptReq(val *DeleteRpcOptReq) *NullableDeleteRpcOptReq {
	return &NullableDeleteRpcOptReq{value: val, isSet: true}
}

func (v NullableDeleteRpcOptReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteRpcOptReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


