/*
Tyrscale Manager API

This is the manager service for Tyrscale

API version: 1.0
Contact: support@starton.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tyrscalesdkgo

import (
	"encoding/json"
)

// checks if the ResponsesDefaultSuccessResponseListPluginsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesDefaultSuccessResponseListPluginsResponse{}

// ResponsesDefaultSuccessResponseListPluginsResponse struct for ResponsesDefaultSuccessResponseListPluginsResponse
type ResponsesDefaultSuccessResponseListPluginsResponse struct {
	Code *int32 `json:"code,omitempty"`
	Data *ListPluginsResponse `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
	Status *int32 `json:"status,omitempty"`
}

// NewResponsesDefaultSuccessResponseListPluginsResponse instantiates a new ResponsesDefaultSuccessResponseListPluginsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesDefaultSuccessResponseListPluginsResponse() *ResponsesDefaultSuccessResponseListPluginsResponse {
	this := ResponsesDefaultSuccessResponseListPluginsResponse{}
	return &this
}

// NewResponsesDefaultSuccessResponseListPluginsResponseWithDefaults instantiates a new ResponsesDefaultSuccessResponseListPluginsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesDefaultSuccessResponseListPluginsResponseWithDefaults() *ResponsesDefaultSuccessResponseListPluginsResponse {
	this := ResponsesDefaultSuccessResponseListPluginsResponse{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ResponsesDefaultSuccessResponseListPluginsResponse) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesDefaultSuccessResponseListPluginsResponse) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ResponsesDefaultSuccessResponseListPluginsResponse) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *ResponsesDefaultSuccessResponseListPluginsResponse) SetCode(v int32) {
	o.Code = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ResponsesDefaultSuccessResponseListPluginsResponse) GetData() ListPluginsResponse {
	if o == nil || IsNil(o.Data) {
		var ret ListPluginsResponse
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesDefaultSuccessResponseListPluginsResponse) GetDataOk() (*ListPluginsResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ResponsesDefaultSuccessResponseListPluginsResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ListPluginsResponse and assigns it to the Data field.
func (o *ResponsesDefaultSuccessResponseListPluginsResponse) SetData(v ListPluginsResponse) {
	o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResponsesDefaultSuccessResponseListPluginsResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesDefaultSuccessResponseListPluginsResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResponsesDefaultSuccessResponseListPluginsResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResponsesDefaultSuccessResponseListPluginsResponse) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ResponsesDefaultSuccessResponseListPluginsResponse) GetStatus() int32 {
	if o == nil || IsNil(o.Status) {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesDefaultSuccessResponseListPluginsResponse) GetStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ResponsesDefaultSuccessResponseListPluginsResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *ResponsesDefaultSuccessResponseListPluginsResponse) SetStatus(v int32) {
	o.Status = &v
}

func (o ResponsesDefaultSuccessResponseListPluginsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesDefaultSuccessResponseListPluginsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableResponsesDefaultSuccessResponseListPluginsResponse struct {
	value *ResponsesDefaultSuccessResponseListPluginsResponse
	isSet bool
}

func (v NullableResponsesDefaultSuccessResponseListPluginsResponse) Get() *ResponsesDefaultSuccessResponseListPluginsResponse {
	return v.value
}

func (v *NullableResponsesDefaultSuccessResponseListPluginsResponse) Set(val *ResponsesDefaultSuccessResponseListPluginsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesDefaultSuccessResponseListPluginsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesDefaultSuccessResponseListPluginsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesDefaultSuccessResponseListPluginsResponse(val *ResponsesDefaultSuccessResponseListPluginsResponse) *NullableResponsesDefaultSuccessResponseListPluginsResponse {
	return &NullableResponsesDefaultSuccessResponseListPluginsResponse{value: val, isSet: true}
}

func (v NullableResponsesDefaultSuccessResponseListPluginsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesDefaultSuccessResponseListPluginsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


