/*
Tyrscale Manager API

This is the manager service for Tyrscale

API version: 1.0
Contact: support@starton.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tyrscalesdkgo

import (
	"encoding/json"
)

// checks if the CreateRecommendationRes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRecommendationRes{}

// CreateRecommendationRes struct for CreateRecommendationRes
type CreateRecommendationRes struct {
	RouteUuid *string `json:"route_uuid,omitempty"`
}

// NewCreateRecommendationRes instantiates a new CreateRecommendationRes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRecommendationRes() *CreateRecommendationRes {
	this := CreateRecommendationRes{}
	return &this
}

// NewCreateRecommendationResWithDefaults instantiates a new CreateRecommendationRes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRecommendationResWithDefaults() *CreateRecommendationRes {
	this := CreateRecommendationRes{}
	return &this
}

// GetRouteUuid returns the RouteUuid field value if set, zero value otherwise.
func (o *CreateRecommendationRes) GetRouteUuid() string {
	if o == nil || IsNil(o.RouteUuid) {
		var ret string
		return ret
	}
	return *o.RouteUuid
}

// GetRouteUuidOk returns a tuple with the RouteUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateRecommendationRes) GetRouteUuidOk() (*string, bool) {
	if o == nil || IsNil(o.RouteUuid) {
		return nil, false
	}
	return o.RouteUuid, true
}

// HasRouteUuid returns a boolean if a field has been set.
func (o *CreateRecommendationRes) HasRouteUuid() bool {
	if o != nil && !IsNil(o.RouteUuid) {
		return true
	}

	return false
}

// SetRouteUuid gets a reference to the given string and assigns it to the RouteUuid field.
func (o *CreateRecommendationRes) SetRouteUuid(v string) {
	o.RouteUuid = &v
}

func (o CreateRecommendationRes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRecommendationRes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RouteUuid) {
		toSerialize["route_uuid"] = o.RouteUuid
	}
	return toSerialize, nil
}

type NullableCreateRecommendationRes struct {
	value *CreateRecommendationRes
	isSet bool
}

func (v NullableCreateRecommendationRes) Get() *CreateRecommendationRes {
	return v.value
}

func (v *NullableCreateRecommendationRes) Set(val *CreateRecommendationRes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRecommendationRes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRecommendationRes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRecommendationRes(val *CreateRecommendationRes) *NullableCreateRecommendationRes {
	return &NullableCreateRecommendationRes{value: val, isSet: true}
}

func (v NullableCreateRecommendationRes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRecommendationRes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


