/*
Tyrscale Manager API

This is the manager service for Tyrscale

API version: 1.0
Contact: support@starton.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tyrscalesdkgo

import (
	"encoding/json"
)

// checks if the DeleteNetworkRes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteNetworkRes{}

// DeleteNetworkRes struct for DeleteNetworkRes
type DeleteNetworkRes struct {
	Name *string `json:"name,omitempty"`
}

// NewDeleteNetworkRes instantiates a new DeleteNetworkRes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteNetworkRes() *DeleteNetworkRes {
	this := DeleteNetworkRes{}
	return &this
}

// NewDeleteNetworkResWithDefaults instantiates a new DeleteNetworkRes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteNetworkResWithDefaults() *DeleteNetworkRes {
	this := DeleteNetworkRes{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DeleteNetworkRes) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteNetworkRes) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DeleteNetworkRes) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DeleteNetworkRes) SetName(v string) {
	o.Name = &v
}

func (o DeleteNetworkRes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteNetworkRes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableDeleteNetworkRes struct {
	value *DeleteNetworkRes
	isSet bool
}

func (v NullableDeleteNetworkRes) Get() *DeleteNetworkRes {
	return v.value
}

func (v *NullableDeleteNetworkRes) Set(val *DeleteNetworkRes) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteNetworkRes) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteNetworkRes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteNetworkRes(val *DeleteNetworkRes) *NullableDeleteNetworkRes {
	return &NullableDeleteNetworkRes{value: val, isSet: true}
}

func (v NullableDeleteNetworkRes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteNetworkRes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


